#!/bin/sh
#
# Copyright (C) 2014 Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

# Create required system users and groups
getent group glance >/dev/null || groupadd -r --gid 164 glance
getent passwd glance >/dev/null || \
	useradd --uid 164 -r -g glance -d /var/lib/glance -s /sbin/nologin \
	-c "OpenStack Glance Daemons" glance

# Create required keystone tenants, users and roles
export OS_SERVICE_TOKEN=##KEYSTONE_TEMPORARY_ADMIN_TOKEN##
export OS_SERVICE_ENDPOINT='http://localhost:35357/v2.0'

keystone user-create --name ##GLANCE_SERVICE_USER## --pass ##GLANCE_SERVICE_PASSWORD##
keystone user-role-add --tenant service --user ##GLANCE_SERVICE_USER## --role admin

keystone service-create --name glance --type image --description "OpenStack Image Service"
keystone endpoint-create  --service-id $(keystone service-list | awk '/ image / {print $2}') \
	    	          --publicurl ##GLANCE_PUBLIC_URL## \
	                  --internalurl ##GLANCE_INTERNAL_URL## \
	                  --adminurl ##GLANCE_ADMIN_URL##

# Setup the glance database
if [ ! -e /var/lib/glance/glance.sqlite ]; then
    chown glance:glance /var/lib/glance
    chown glance:glance /var/log/glance
    sudo -u glance glance-manage db_sync
fi

rm /etc/systemd/system/multi-user.target.wants/openstack-glance-setup.service

systemctl start openstack-glance-api
systemctl start openstack-glance-registry

ln -s "/etc/systemd/system/openstack-glance-api.service" \
    "/etc/systemd/system/multi-user.target.wants/openstack-glance-api.service"

ln -s "/etc/systemd/system/openstack-glance-registry.service" \
    "/etc/systemd/system/multi-user.target.wants/openstack-glance-registry.service"

exit 0
