#!/bin/sh
#
# Copyright (C) 2014 Codethink Limited
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -xe

# Reconfigure LVM to scan only the devices that contain the
# cinder-volume volume group
sed -i 's|# filter = \[ \"a\/\.\*\/\" \]|filter = \[ \"a\/sdb1\/\", \"r\/\.\*\/\" \]|' \
	/etc/lvm/lvm.conf

# Create the cinder LVM type and set a volume backend name
export OS_USERNAME=temporary_admin
export OS_PASSWORD=veryinsecure
export OS_TENANT_NAME=admin
export OS_AUTH_URL=http://localhost:35357/v2.0
cinder type-create lvms
cinder type-key lvms set volume_backend_name=LVM_iSCSI

# Create initiatorname.iscsi file
mkdir -p "$DESTDIR"/etc/iscsi
echo "InitiatorName=$(iscsi-iname)" > /etc/iscsi/initiatorname.iscsi

# Run the target service required for attaching volumes
depmod -a
systemctl enable target.service
systemctl start target.service

exit 0
